version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nest-server:
    image: nestjs-app-image
    build:
      context: .
    env_file:
      - .env
    container_name: nest-server
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres:
